### PR TITLE
Add support for custom async confirmation handler

### PR DESCRIPTION
**Pull request by krasnoukhov**
This could be useful to people who use custom-styled dialog modals. Obviously this will only work if ember transition is triggered (not a hard refresh).

- [ ] Better test for `_transitionConfirmed` state
- [ ] Documentation?

Example using sweetalert:

confirmation

### CODE REVIEW

**Comment by krasnoukhov** [comment]
Hey, any feedback here? I'm wiling to rebase/polish this in case it can be merged

**Comment by blimmer** [comment]
Hi @krasnoukhov - I think it'd be OK to expose logic like this. The only part I'm not sure about is the `_transitionConfirmed` state. What do you think about simplifying this logic down to be only the `customConfirm` method that takes a promise? That way, state wouldn't need to be managed with the `_transitionConfirmed` property.

**Comment by krasnoukhov** [comment]
@blimmer Thanks for the feedback! Maybe I'm missing something here, but `_transitionConfirmed` exists just so we can first `abort` the transition and then either `retry` or do nothing. I'm not sure how to achieve this kind of flow with just the promise. Any ideas?

**Comment by tylerturdenpants** [comment]
@jasonmit @blimmer is there any way that we could get some movement on this?  I'd appreciate this being available upstream.  

Also, do you need a new maintainer? I'd be willing to do some of the chore work to make sure this is available for Octane.

**Comment by jasonmit** [comment]
@tylerturdenpants I would love another maintainer :)  I am currently not active in the Ember space and would love all the help I can get so that the community does not suffer.

I'll work on adding you here and on npm now.  Feel free to ping on twitter [@_jasonmit](https://twitter.com/_jasonmit) if you have any questions/issues that need my attention.

**Comment by tylerturdenpants** [comment]
@jasonmit Thank you very much.  I handle a few other ember related things so I know my way around.  I will make you proud.

**Comment by jasonmit** [comment]
Should be all set now - invites sent :)  Much appreciated!

**Pull request merged**
