### PR TITLE
Upgrade to ember-cli 2.5.0

### PR DESCRIPTION
**Pull request by blimmer**

### CODE REVIEW

**Comment by jasonmit** [comment]
Thanks!

**Comment by blimmer** [comment]
No problem - will you consider a release?

**Comment by jasonmit** [comment]
Yup, will release when I get near my computer and will also add you as owner for the future

**Comment by jasonmit** [comment]
@blimmer added you as collaborator here and npm owner.  I'll let you version this one as well and feel free to version & merge at will.

Thanks

**Comment by blimmer** [comment]
Excellent - thank you. Published 0.3.0.

**Pull request merged**
